# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaddons < Formula
  desc "Kubernetes addon compatibility checker powered by Gemini AI"
  homepage "https://github.com/qbandev/kaddons"
  version "0.4.2"
  license "MIT"

  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.4.2/kaddons_0.4.2_darwin_amd64.tar.gz"
      sha256 "8c277016b864e2c4bdfa5f7f12e2014522daa70fa047fa3681b1279a920451cc"

      define_method(:install) do
        bin.install "kaddons"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.4.2/kaddons_0.4.2_darwin_arm64.tar.gz"
      sha256 "54a1d820ebf3c16ee2a9c5f659d0965ba7e29fb4c25c58cde9a63ee04911e578"

      define_method(:install) do
        bin.install "kaddons"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.4.2/kaddons_0.4.2_linux_amd64.tar.gz"
      sha256 "8efb9d1dab38c6dc681ee7fb2e870009e417012275a353e626d092de89e330ca"
      define_method(:install) do
        bin.install "kaddons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.4.2/kaddons_0.4.2_linux_arm64.tar.gz"
      sha256 "fc809e0c429ddc38cf12b429350729b1f8157b40dc002f9e27acbac1e4720038"
      define_method(:install) do
        bin.install "kaddons"
      end
    end
  end

  test do
    system "#{bin}/kaddons --version"
  end
end
