# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaddons < Formula
  desc "Kubernetes addon compatibility checker powered by Gemini AI"
  homepage "https://github.com/qbandev/kaddons"
  version "0.5.0"
  license "MIT"

  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.5.0/kaddons_0.5.0_darwin_amd64.tar.gz"
      sha256 "b1e3ec3d282dd238eedc1fc59dedd8a9850c99347fd23887c6e1dd8a753f05ee"

      define_method(:install) do
        bin.install "kaddons"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.5.0/kaddons_0.5.0_darwin_arm64.tar.gz"
      sha256 "f1f20664af783154454e1dc1b2cfa75994dc5737c87dfa5495738a372a818e3e"

      define_method(:install) do
        bin.install "kaddons"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.5.0/kaddons_0.5.0_linux_amd64.tar.gz"
      sha256 "2546575b41339f8637437332099cdb213846d13bbd7227cc8ff192877de7e3eb"
      define_method(:install) do
        bin.install "kaddons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.5.0/kaddons_0.5.0_linux_arm64.tar.gz"
      sha256 "983e5ec73b8c47dbe361e46cf763e999ef5c347590f9e8479d8444ce6c966b2d"
      define_method(:install) do
        bin.install "kaddons"
      end
    end
  end

  test do
    system "#{bin}/kaddons --version"
  end
end
