# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kaddons < Formula
  desc "Kubernetes addon compatibility checker powered by Gemini AI"
  homepage "https://github.com/qbandev/kaddons"
  version "0.2.2"
  license "MIT"

  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.2.2/kaddons_0.2.2_darwin_amd64.tar.gz"
      sha256 "d4830cc6b640fcac58e05354ee0e6a572d086d410de38a196fd83ce4a70d9cc6"

      define_method(:install) do
        bin.install "kaddons"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.2.2/kaddons_0.2.2_darwin_arm64.tar.gz"
      sha256 "b5848cceb5dd131407bb91745108a9d490a1600847a626d374314d7f1aba6485"

      define_method(:install) do
        bin.install "kaddons"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.2.2/kaddons_0.2.2_linux_amd64.tar.gz"
      sha256 "7be5877d3ec1185730b6d6f9c6fc498f2d26515577d013580ba09622ea84d1e3"
      define_method(:install) do
        bin.install "kaddons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Qbandev/kaddons/releases/download/v0.2.2/kaddons_0.2.2_linux_arm64.tar.gz"
      sha256 "163507b13e87001aefebdf6a6498282612024637459f90234b1edd4924183482"
      define_method(:install) do
        bin.install "kaddons"
      end
    end
  end

  test do
    system "#{bin}/kaddons --version"
  end
end
